import "~/styles/globals.css";
import "@radix-ui/themes/styles.css";

import { Inter } from "next/font/google";
import {
  Button,
  Container,
  Flex,
  Heading,
  Separator,
  Theme,
} from "@radix-ui/themes";
import Link from "next/link";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Theme>
            <Flex align={"center"} py="2" height="60px">
              <Container size={"3"}>
                <Flex justify={"between"}>
                  <Link href={"/"}>
                    <Heading as={"h1"}>Tech-quiz</Heading>
                  </Link>

                  <SignedIn>
                    <UserButton />
                  </SignedIn>
                  <SignedOut>
                    <SignInButton>
                      <Button>sign in</Button>
                    </SignInButton>
                  </SignedOut>
                </Flex>
              </Container>
            </Flex>
            <Separator my="3" size="4" />
            <Container size={"3"}>{children}</Container>
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
