import "~/styles/globals.css";
import "@radix-ui/themes/styles.css";

import { Inter } from "next/font/google";
import { Container, Theme } from "@radix-ui/themes";
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "~/app/_components/navbar";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Theme>
            <Navbar></Navbar>
            <Container px={"4"} size={"3"}>
              {children}
            </Container>
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
